### ISSUE TITLE
Redux-toolkit

### ISSUE THREAD

**Issue by Carduelis** [dxvil/ecommerce-react-redux#2]
В следующем проекте стоит попробовать использовать эту библиоетку.
Поняв принцип action/reducer, иммутабельности стора, можно переходить на что-то более удобное.
Сам Редакс -- это довольно низкоуровневая и неудобная система управления стэйтом. Хорошая, но одна из многих, очень многословная и неудобная.

https://github.com/dxvil/ecommerce-react-redux/blob/187a671e49a1e1438851b34e05b23a00f28cd147/src/redux/reducers/filterShopReducer.js#L17

**Comment by dxvil** [comment]
Спасибо, реально удобная вещь, буду пробовать
